config/routes.rb
Rails.application.routes.draw do

  resources :printers
  get '/works/new_import', to: 'works#new_import'
  post '/works/import', to: 'works#import'

  resources :works
  
  root to: 'reporte#upload'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/printer.rb
class Printer < ApplicationRecord
  has_many :works
end

app/models/work.rb
class Work < ApplicationRecord
  belongs_to :printer

  # Formato de impresiones Docucolor
  LOG_FORMAT = /(.*)\t(.*)\t(.*)\t(.*)\t(.*)\t(.*)\t(.*)\t(.*)\t(.*)\t(.*)\t(.*)/

  def import import_file
    # Abrir el archivo subido por el usuario
    report = File.open(import_file)

    # Flag para descartar las primeras dos lineas 
    flag = 0

    # Ciclo de extraccion de datos y grabado a la base de datos 
    report.each do |line|
      if flag == 0 || flag == 1
        # Do nothing
      else
        # Parsear el documento a string, luego quebrarlos por columnas y guardarlo a un arreglo
        # luego grabarlo a una variable tipo work y salvar a la base de datos 
        record = line.to_s
        data = record.split(/(.*)\t(.*)\t(.*)\t(.*)\t(.*)\t(.*)\t(.*)\t(.*)\t(.*)\t(.*)\t(.*)/)
        work = Work.new
        
        number = 0
        data.each do |d|
          case number
          when 0
            number += 1
          when 1
            work.nombre = d
            number += 1
          when 2
            work.tamano_de_papel = d
            number += 1
          when 3
            work.tipo_de_papel = d
            number += 1
          when 4
            work.numero_de_paginas_impresas = d
            number += 1
          when 5
            work.fecha = d
            number += 1
          when 6
            work.estado_de_impresion = d
            number += 1
          when 7
            work.usuario = d
            number += 1 
          when 8
            work.numero_de_paginas_blanco_negro = d
            number += 1
          when 9
            work.numero_de_paginas_a_color = d
            number += 1 
          when 10
            work.numero_de_copias_impresas = d
            number += 1
          when 11
            work.paginas = d
            p = Printer.find(1)
            work.printer_id = p.id
            work.save
          end
        end
      end
      flag+= 1
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/printers_controller.rb
class PrintersController < ApplicationController
  before_action :set_printer, only: [:show, :edit, :update, :destroy]

  # GET /printers
  # GET /printers.json
  def index
    @printers = Printer.all
  end

  # GET /printers/1
  # GET /printers/1.json
  def show
  end

  # GET /printers/new
  def new
    @printer = Printer.new
  end

  # GET /printers/1/edit
  def edit
  end

  # POST /printers
  # POST /printers.json
  def create
    @printer = Printer.new(printer_params)

    respond_to do |format|
      if @printer.save
        format.html { redirect_to @printer, notice: 'Printer was successfully created.' }
        format.json { render :show, status: :created, location: @printer }
      else
        format.html { render :new }
        format.json { render json: @printer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /printers/1
  # PATCH/PUT /printers/1.json
  def update
    respond_to do |format|
      if @printer.update(printer_params)
        format.html { redirect_to @printer, notice: 'Printer was successfully updated.' }
        format.json { render :show, status: :ok, location: @printer }
      else
        format.html { render :edit }
        format.json { render json: @printer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /printers/1
  # DELETE /printers/1.json
  def destroy
    @printer.destroy
    respond_to do |format|
      format.html { redirect_to printers_url, notice: 'Printer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_printer
      @printer = Printer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def printer_params
      params.require(:printer).permit(:name)
    end
end

app/controllers/reporte_controller.rb
class ReporteController < ApplicationController
  def upload
  end
end

app/controllers/works_controller.rb
class WorksController < ApplicationController
  before_action :set_work, only: [:show, :edit, :update, :destroy]

  # GET /works
  # GET /works.json
  def index
    @works = Work.all
  end

  # GET /works/1
  # GET /works/1.json
  def show
  end

  # GET /works/new
  def new
    @work = Work.new
  end

  # GET /works/1/edit
  def edit
  end

  # POST /works
  # POST /works.json
  def create
    @work = Work.new(work_params)
    respond_to do |format|
      if @work.save
        format.html { redirect_to @work, notice: 'Work was successfully created.' }
        format.json { render :show, status: :created, location: @work }
      else
        format.html { render :new }
        format.json { render json: @work.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /works/1
  # PATCH/PUT /works/1.json
  def update
    respond_to do |format|
      if @work.update(work_params)
        format.html { redirect_to @work, notice: 'Work was successfully updated.' }
        format.json { render :show, status: :ok, location: @work }
      else
        format.html { render :edit }
        format.json { render json: @work.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /works/1
  # DELETE /works/1.json
  def destroy
    @work.destroy
    respond_to do |format|
      format.html { redirect_to works_url, notice: 'Work was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def new_import
    @work = Work.new
  end

  def import
    @work = Work.new 
    begin
      @work.import(params[:work][:import_file])
      puts "Aqui despues de mandar a llamar import en el controlador"
      flash[:success] = "<strong> Trabajos importados!</strong>"
      redirect_to works_path

    rescue => exception
      flash[:error] = "Hubo un error al subir tu archivo"
      puts "EL ACZINO MATANDO"
      redirect_to works_path
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_work
      @work = Work.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def work_params
      params.require(:work).permit(:nombre, :tamano_de_papel, :tipo_de_papel, :numero_de_paginas_impresas, :fecha, :estado_de_impresion, :usuario, :numero_de_paginas_blanco_negro, :numero_de_paginas_a_color, :numero_de_copias_impresas, :paginas)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/printers_helper.rb
module PrintersHelper
end

app/helpers/reporte_helper.rb
module ReporteHelper
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Printify</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/printers/_form.html.erb
<%= form_with(model: printer, local: true) do |form| %>
  <% if printer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(printer.errors.count, "error") %> prohibited this printer from being saved:</h2>

      <ul>
        <% printer.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/printers/edit.html.erb
<h1>Editing Printer</h1>

<%= render 'form', printer: @printer %>

<%= link_to 'Show', @printer %> |
<%= link_to 'Back', printers_path %>

app/views/printers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Printers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @printers.each do |printer| %>
      <tr>
        <td><%= printer.name %></td>
        <td><%= link_to 'Show', printer %></td>
        <td><%= link_to 'Edit', edit_printer_path(printer) %></td>
        <td><%= link_to 'Destroy', printer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Printer', new_printer_path %>

app/views/printers/new.html.erb
<h1>New Printer</h1>

<%= render 'form', printer: @printer %>

<%= link_to 'Back', printers_path %>

app/views/printers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @printer.name %>
</p>

<%= link_to 'Edit', edit_printer_path(@printer) %> |
<%= link_to 'Back', printers_path %>

app/views/reporte/upload.html.erb
<div class="container">
    <h1>Printify</h1>
    <form>
        <div class="form-group">
            <label for="exampleFormControlFile1">Escoge tu archivo de texto a analizar</label>
            <input type="file" class="form-control-file" id="exampleFormControlFile1">
        </div>
    </form>
    <button type="button" class="btn btn-primary">Upload</button>
</div>

app/views/works/_form.html.erb
<%= form_with(model: work, local: true) do |form| %>
  <% if work.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(work.errors.count, "error") %> prohibited this work from being saved:</h2>

      <ul>
        <% work.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre %>
  </div>

  <div class="field">
    <%= form.label :tamano_de_papel %>
    <%= form.text_field :tamano_de_papel %>
  </div>

  <div class="field">
    <%= form.label :tipo_de_papel %>
    <%= form.text_field :tipo_de_papel %>
  </div>

  <div class="field">
    <%= form.label :numero_de_paginas_impresas %>
    <%= form.text_field :numero_de_paginas_impresas %>
  </div>

  <div class="field">
    <%= form.label :fecha %>
    <%= form.text_field :fecha %>
  </div>

  <div class="field">
    <%= form.label :estado_de_impresion %>
    <%= form.text_field :estado_de_impresion %>
  </div>

  <div class="field">
    <%= form.label :usuario %>
    <%= form.text_field :usuario %>
  </div>

  <div class="field">
    <%= form.label :numero_de_paginas_blanco_negro %>
    <%= form.text_field :numero_de_paginas_blanco_negro %>
  </div>

  <div class="field">
    <%= form.label :numero_de_paginas_a_color %>
    <%= form.text_field :numero_de_paginas_a_color %>
  </div>

  <div class="field">
    <%= form.label :numero_de_copias_impresas %>
    <%= form.text_field :numero_de_copias_impresas %>
  </div>

  <div class="field">
    <%= form.label :paginas %>
    <%= form.text_field :paginas %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/works/edit.html.erb
<h1>Editing Work</h1>

<%= render 'form', work: @work %>

<%= link_to 'Show', @work %> |
<%= link_to 'Back', works_path %>

app/views/works/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Works</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Tamano de papel</th>
      <th>Tipo de papel</th>
      <th>Numero de paginas impresas</th>
      <th>Fecha</th>
      <th>Estado de impresion</th>
      <th>Usuario</th>
      <th>Numero de paginas blanco negro</th>
      <th>Numero de paginas a color</th>
      <th>Numero de copias impresas</th>
      <th>Paginas</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @works.each do |work| %>
      <tr>
        <td><%= work.nombre %></td>
        <td><%= work.tamano_de_papel %></td>
        <td><%= work.tipo_de_papel %></td>
        <td><%= work.numero_de_paginas_impresas %></td>
        <td><%= work.fecha %></td>
        <td><%= work.estado_de_impresion %></td>
        <td><%= work.usuario %></td>
        <td><%= work.numero_de_paginas_blanco_negro %></td>
        <td><%= work.numero_de_paginas_a_color %></td>
        <td><%= work.numero_de_copias_impresas %></td>
        <td><%= work.paginas %></td>
        <td><%= link_to 'Show', work %></td>
        <td><%= link_to 'Edit', edit_work_path(work) %></td>
        <td><%= link_to 'Destroy', work, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Work', new_work_path %>

app/views/works/new.html.erb
<h1>New Work</h1>

<%= render 'form', work: @work %>

<%= link_to 'Back', works_path %>

app/views/works/new_import.html.erb
<%= form_for @work, url: works_import_path, html: { multipart: true } do |f| %>
  <%= f.file_field :import_file %>
  <%= f.submit "Save", class: "btn btn-primary" %>
<% end %>

app/views/works/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @work.nombre %>
</p>

<p>
  <strong>Tamano de papel:</strong>
  <%= @work.tamano_de_papel %>
</p>

<p>
  <strong>Tipo de papel:</strong>
  <%= @work.tipo_de_papel %>
</p>

<p>
  <strong>Numero de paginas impresas:</strong>
  <%= @work.numero_de_paginas_impresas %>
</p>

<p>
  <strong>Fecha:</strong>
  <%= @work.fecha %>
</p>

<p>
  <strong>Estado de impresion:</strong>
  <%= @work.estado_de_impresion %>
</p>

<p>
  <strong>Usuario:</strong>
  <%= @work.usuario %>
</p>

<p>
  <strong>Numero de paginas blanco negro:</strong>
  <%= @work.numero_de_paginas_blanco_negro %>
</p>

<p>
  <strong>Numero de paginas a color:</strong>
  <%= @work.numero_de_paginas_a_color %>
</p>

<p>
  <strong>Numero de copias impresas:</strong>
  <%= @work.numero_de_copias_impresas %>
</p>

<p>
  <strong>Paginas:</strong>
  <%= @work.paginas %>
</p>

<%= link_to 'Edit', edit_work_path(@work) %> |
<%= link_to 'Back', works_path %>